settengs:
  group_id: id
  group_token: key
  session: false
  keyboard: false
  wrongpasswrd: true
  length:
    min: 5
    max: 16
  blocked:
    move: true
    dropitem: true
    damage: true
    blockbreak: true
    blockplace: true
    inventoryclick: true
    pickup: true
    chat: true
    cmd: true
help:
  register: '&cAUTH &e> &fИспользуйте &e/register [пароль]'
  login: '&cAUTH &e> &fИспользуйте &e/login  [пароль]'
  changepassword: '&cAUTH &e> &fИспользуйте &e/cp [старый пароль] [новый пароль]'
notyfications:
  register:
    - '&cAUTH &e> &fНеобходимо пройти регистрацию'
    - '&cAUTH &e> &fИспользуйте /register [пароль]'
  login:
    - '&cAUTH &e> &fНеобходимо пройти авторизацию'
    - '&cAUTH &e> &fИспользуйте /login [пароль]'
  code:
    - '&cAUTH &e> &fНеобходимо подтвердить вход'
    - '&cAUTH &e> &fИспользуйте /code [код]'
  accept:
    - '&cAUTH &e> &fНеобходимо подтвердить вход'
    - '&cAUTH &e> &fПерейдите в сообщения группы'
vk:
  send: 'На ваш аккаунт вошли. Код подтверждения: $code'
  good: 'Вход прошел успешно.'
  badly: 'Вход отменён успешно.'
  keyboard:
    message: 'На ваш аккаунт произведена попытка входа. Айпи: $ip. Ник: $name'
    buttons:
      accept: 'Разрешить'
      decline: 'Запретить'
    kick: '&cAUTH &e> &fВход был запрещён.'
    accept:
      - '&cAUTH &e> &fАвторизация прошла успешно.'
      - '&cAUTH &e> &fПриятной игры на сервера MyServer'
  recover: 'Новый пароль: $pass'
  haventkeyboard: 'Это действие отключено'
  haventaccept: 'Нет активного запроса на подтверждение'
  access:
    text: '&cAUTH &e> &fВы получили запрос на привязку аккаунта к странице от (&9$name&f).'
    accept: '&aПринять'
    decline: '&cОтклонить'
  online: 'Игрок не онлайн'
  newpassword: 'Пароль был успешно изменён. Новый пароль: $pass'
  events:
    connect: 'привязать'
    disconnect: 'отвязать'
    recover: 'восстановить'
  disconnect: 'Страница успешно отвязана от аккаунта.'
  connect:
    help: 'Для привязки используйте: Привязать [ник]'
    haveconnect: 'Ваша страница уже привязана к нику $player'
    haventconnect: 'Ваша страница не привязана к аккаунту'
    send: 'Подтвердите привязку в на сервере.'
    auth: 'Перед привязкой нужно быть авторизованным'
    accept: 'Запрос принят. Аккаунт привязан. Отвязать - позволяет отвязать аккаунт от вашей страницы. Восстановить - генерирует новый пароль'
    decline: 'Запрос отклонён. Аккаунт не привязан.'
messages:
  isregister: '&cAUTH &e> &fВы уже зарегистрированы!'
  autorize: '&cAUTH &e> &fВы уже авторизованы!'
  permission: '&cAUTH &e> &fУ вас не достаточно прав'
  minpassword: '&cAUTH &e> &fМинимальный пароль должен состоять из $count символов'
  maxpassword: '&cAUTH &e> &fМинимальный пароль должен состоять из $count символов'
  playernotfound: '&cAUTH &e> &fИгрок не найден'
  noverify: '&cAUTH &e> &fПароли не совпадают!'
  vk:
    accept: '&cAUTH &e> &fПривязка принята'
    decline: '&cAUTH &e> &fПривязка отклонена'
    empty: '&cAUTH &e> &fУ вас нет запросов на привязку'
  wrongpasswrd: '&cAUTH &e> &fПароль не верный'
  wrongaccept: '&cAUTH &e> &fВход запрещён'
  oldwrongpasswrd: '&cAUTH &e> &fСтарый пароль не верный'
  succesfull:
    register:
      - '&cAUTH &e> &fАккаунт успешно зарегистрирован!'
      - '&cAUTH &e> &fВаш пароль: $pass. Никому его не говорите!'
    login:
      - '&cAUTH &e> &fАвторизация прошла успешно.'
      - '&cAUTH &e> &fПриятной игры на сервере'
    code:
      - '&cAUTH &e> &fАвторизация прошла успешно.'
      - '&cAUTH &e> &fПриятной игры на сервере'
    changepassword:
      - '&cAUTH &e> &fПароль успешно изменён.'
      - '&cAUTH &e> &fВаш пароль: $pass. Никому его не говорите!'
    disconnect:
      - '&cAUTH &e> &fАккаунт был отвязан от ващей страницы.'
    session:
      - '&cAUTH &e> &fСессия активна. Пароль вводить не нужно'
      - '&cAUTH &e> &fПриятной игры на сервере'
  reference:
    - '&cAUTH &e> &fУ вас нет активной привязки к ВКонтакте'
    - '&cAUTH &e> &fДля привязки перейдите в группу https://vk.com/hc.play'
    - '&cAUTH &e> &fНапишите: &eПривязать $player'
