settengs:
  group_id: 127876037
  group_token: PQOWEFQOGQWDFUIQHNWEUFQHEFJQNEWIFNQOIWENF
  session: true
messages:
  isregister: '&cAUTH &e> &fВы уже зарегистрированы!'
  autorize: '&cAUTH &e> &fВы уже авторизованы!'
  noverify: '&cAUTH &e> &fПароли не совпадают!'
  succesfull:
    - '&cAUTH &e> &fАккаунт успешно зарегистрирован!'
    - '&cAUTH &e> &fВаш пароль: $pass. Никому его не говорите!'
